language: c
git:
    submodules: false
before_install:
    - sudo add-apt-repository ppa:avsm/ppa
    - sudo apt-get update
    - sudo apt-get install coq coq-theories ocaml ocamlfind xml-light bisect opam
    - wget https://raw.githubusercontent.com/brownplt/LambdaS5/master/envs/es5.env
    - ./get_deps.sh
install:
    - make -C LambdaS5/ native
    - ./LambdaS5/build/eval.native es5.env -save /tmp/store.dump
script:
    - make -C LambdaS5/ tests
