language: c
git:
    submodules: false
before_install:
    - sudo apt-get update
    - sudo apt-get install aptitude
    - echo "yes" | sudo add-apt-repository ppa:avsm/ocaml41+opam11
    - echo "yes" | sudo add-apt-repository ppa:glondu/ppa
    - sudo aptitude update 
    - sudo aptitude install -y coq ocaml proofgeneral
    - wget https://raw.githubusercontent.com/brownplt/LambdaS5/master/envs/es5.env
    - ./get_deps.sh
install:
    - make -C LambdaS5/ native
    - ./LambdaS5/build/eval.native es5.env -save /tmp/store.dump
script:
    - make -C LambdaS5/ tests
