language: c
git:
    submodules: false
before_install:
    - sudo apt-get update
    - sudo apt-get install coq coq-theories ocaml ocaml-native-compilers camlp4-extra libcoq-ocaml ocaml-base-nox
    - echo "yes" | sudo add-apt-repository ppa:avsm/ocaml41+opam11
    - sudo apt-get update
    - sudo apt-get install opam
    - sudo opam install ocamlfind
    - sudo opam install xml-light
    - sudo opam install bisect 
    - wget https://raw.githubusercontent.com/brownplt/LambdaS5/master/envs/es5.env
    - ./get_deps.sh
install:
    - make -C LambdaS5/ native
    - ./LambdaS5/build/eval.native es5.env -save /tmp/store.dump
script:
    - make -C LambdaS5/ tests
